### ISSUE TITLE
[Enhancement] Add more details in the "Strength" page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/Passliss#153]
### Enhancement

Add more details in the "Strength" page, such as: 

- [x] The number of capital letters
- [x] The number of lower case letters
- [x] The number of special characters used
- [x] The number of digits
- [x] The length of password 

### Other informations

Add a `Button` that brings the user to a dedicated section.
